### ISSUE TITLE
Where is the code? Repo is logically empty.

### ISSUE THREAD

**Issue by accessallow** [ericouyang/blog50#1]
I saw your video on youtube About cs50:Laravel app and really liked it.It helped me greatly with my new laravel concepts. Also your way of speaking and delivery is very impressive. 
https://www.youtube.com/watch?v=XwhZ4xX7Qmc

Sorry to interrupt you this way, but You said about some interesting things in code about production. I see here the code you posted on github is logically empty. No migrations etc. Do you have the code posted somewhere else?

**Comment by ericouyang** [comment]
Thanks for reaching out! The completed code is available in a separate branch within the repository. Specifically you should look at the "completed" branch: https://github.com/ericouyang/blog50/tree/completed

**Comment by accessallow** [comment]
Thankyou very much eric.
